"""link spare parts to the component type they serve

Revision ID: 13c51d61060c
Revises: 1b64ad5cf014
Create Date: 2026-08-11 00:08:51.141741
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '13c51d61060c'
down_revision: str | None = '1b64ad5cf014'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spare_parts', sa.Column('component_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spare_parts', 'component_type')
    # ### end Alembic commands ###
