"""atribut rantai pasok pada spare_parts

Revision ID: 1b64ad5cf014
Revises: 8b1ddbca3e46
Create Date: 2026-08-06 16:29:23.718654
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1b64ad5cf014'
down_revision: str | None = '8b1ddbca3e46'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spare_parts', sa.Column('static_criticality', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('spare_parts', sa.Column('lead_time_weeks', sa.Integer(), nullable=True))
    op.add_column('spare_parts', sa.Column('vendor_count', sa.Integer(), nullable=True))
    op.add_column('spare_parts', sa.Column('primary_vendor', sa.String(length=255), nullable=True))
    op.create_check_constraint(op.f('ck_spare_parts_nonnegative_lead_time'), 'spare_parts', 'lead_time_weeks IS NULL OR lead_time_weeks >= 0')
    op.create_check_constraint(op.f('ck_spare_parts_static_criticality_range'), 'spare_parts', 'static_criticality IS NULL OR (static_criticality >= 0 AND static_criticality <= 1)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_spare_parts_static_criticality_range'), 'spare_parts', type_='check')
    op.drop_constraint(op.f('ck_spare_parts_nonnegative_lead_time'), 'spare_parts', type_='check')
    op.drop_column('spare_parts', 'primary_vendor')
    op.drop_column('spare_parts', 'vendor_count')
    op.drop_column('spare_parts', 'lead_time_weeks')
    op.drop_column('spare_parts', 'static_criticality')
    # ### end Alembic commands ###
