"""skema kanonik awal

Revision ID: 8b1ddbca3e46
Revises: 
Create Date: 2026-08-06 16:20:05.804913
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8b1ddbca3e46'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_causes')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_causes_canonical_id')),
    sa.UniqueConstraint('code', name=op.f('uq_causes_code'))
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_document_id', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('technician_note', 'inspection_report', 'manual', 'datasheet', 'rcps', 'fmea', 'other')", name=op.f('ck_documents_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_documents_canonical_id')),
    sa.UniqueConstraint('source_system', 'source_document_id', name='uq_documents_source_document')
    )
    op.create_index('ix_documents_document_type', 'documents', ['document_type'], unique=False)
    op.create_table('failure_modes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failure_modes')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_failure_modes_canonical_id')),
    sa.UniqueConstraint('code', name=op.f('uq_failure_modes_code'))
    )
    op.create_table('maintenance_notifications',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('notification_number', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_notifications')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_maintenance_notifications_canonical_id')),
    sa.UniqueConstraint('notification_number', name=op.f('uq_maintenance_notifications_notification_number'))
    )
    op.create_table('operating_states',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operating_states')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_operating_states_canonical_id')),
    sa.UniqueConstraint('code', name=op.f('uq_operating_states_code'))
    )
    op.create_table('plants',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_plants_canonical_id')),
    sa.UniqueConstraint('code', name=op.f('uq_plants_code'))
    )
    op.create_table('semantic_concepts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('concept_type', sa.String(length=50), nullable=False),
    sa.Column('preferred_label', sa.String(length=1000), nullable=False),
    sa.Column('normalized_label', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("concept_type IN ('activity', 'component_type', 'damage', 'cause')", name=op.f('ck_semantic_concepts_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_concepts')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_semantic_concepts_canonical_id')),
    sa.UniqueConstraint('concept_type', 'normalized_label', name='uq_semantic_concept_label')
    )
    op.create_table('spare_parts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spare_parts')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_spare_parts_canonical_id')),
    sa.UniqueConstraint('part_number', name=op.f('uq_spare_parts_part_number'))
    )
    op.create_table('symptoms',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptoms')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_symptoms_canonical_id')),
    sa.UniqueConstraint('code', name=op.f('uq_symptoms_code'))
    )
    op.create_table('technicians',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('employee_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_technicians_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technicians')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_technicians_canonical_id')),
    sa.UniqueConstraint('employee_number', name=op.f('uq_technicians_employee_number'))
    )
    op.create_table('document_versions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_uri', sa.String(length=1000), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'content_hash', name='uq_document_versions_document_hash'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_versions_document_version')
    )
    op.create_index('ix_document_versions_document_id', 'document_versions', ['document_id'], unique=False)
    op.create_table('notification_concept_links',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('semantic_concept_id', sa.Uuid(), nullable=False),
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relationship_type IN ('affects_part','reports_damage','has_cause')", name=op.f('ck_notification_concept_links_type')),
    sa.CheckConstraint("review_status IN ('unreviewed','accepted','rejected')", name=op.f('ck_notification_concept_links_review_status')),
    sa.ForeignKeyConstraint(['notification_id'], ['maintenance_notifications.id'], name=op.f('fk_notification_concept_links_notification_id_maintenance_notifications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semantic_concept_id'], ['semantic_concepts.id'], name=op.f('fk_notification_concept_links_semantic_concept_id_semantic_concepts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_concept_links')),
    sa.UniqueConstraint('notification_id', 'source_item_id', 'relationship_type', name='uq_notification_concept_source_relation')
    )
    op.create_table('production_lines',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_production_lines_plant_id_plants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_lines')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_production_lines_canonical_id')),
    sa.UniqueConstraint('plant_id', 'code', name='uq_production_lines_plant_code')
    )
    op.create_index('ix_production_lines_plant_id', 'production_lines', ['plant_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_document_chunks_nonnegative_index')),
    sa.CheckConstraint('start_offset >= 0 AND end_offset > start_offset', name=op.f('ck_document_chunks_valid_offsets')),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_chunks_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_version_id', 'chunk_index', name='uq_document_chunks_version_index')
    )
    op.create_index('ix_document_chunks_document_version_id', 'document_chunks', ['document_version_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('production_line_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('tag_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('commissioned_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'maintenance', 'retired')", name=op.f('ck_equipment_status')),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], name=op.f('fk_equipment_production_line_id_production_lines'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_equipment_canonical_id')),
    sa.UniqueConstraint('tag_number', name=op.f('uq_equipment_tag_number'))
    )
    op.create_index('ix_equipment_equipment_type', 'equipment', ['equipment_type'], unique=False)
    op.create_index('ix_equipment_production_line_id', 'equipment', ['production_line_id'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('tag_number', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'maintenance', 'retired')", name=op.f('ck_components_status')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_components_equipment_id_equipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_components')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_components_canonical_id')),
    sa.UniqueConstraint('equipment_id', 'tag_number', name='uq_components_equipment_tag_number')
    )
    op.create_index('ix_components_component_type', 'components', ['component_type'], unique=False)
    op.create_index('ix_components_equipment_id', 'components', ['equipment_id'], unique=False)
    op.create_table('equipment_operating_states',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('operating_state_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.CheckConstraint('ended_at IS NULL OR ended_at > started_at', name=op.f('ck_equipment_operating_states_valid_time_range')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_equipment_operating_states_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operating_state_id'], ['operating_states.id'], name=op.f('fk_equipment_operating_states_operating_state_id_operating_states'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_operating_states')),
    sa.UniqueConstraint('equipment_id', 'started_at', name='uq_equipment_operating_states_equipment_start')
    )
    op.create_index('ix_equipment_operating_states_equipment_time', 'equipment_operating_states', ['equipment_id', 'started_at', 'ended_at'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('extractor_version', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('evidence_format', sa.String(length=30), server_default=sa.text("'text'"), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evidence_format IN ('text', 'table', 'image')", name=op.f('ck_evidence_format')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_evidence_confidence_range')),
    sa.CheckConstraint('start_offset >= 0 AND end_offset > start_offset', name=op.f('ck_evidence_valid_offsets')),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], name=op.f('fk_evidence_document_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index('ix_evidence_document_chunk_id', 'evidence', ['document_chunk_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('work_order_number', sa.String(length=100), nullable=False),
    sa.Column('work_order_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('source_order_type', sa.String(length=50), nullable=True),
    sa.Column('source_priority', sa.String(length=50), nullable=True),
    sa.Column('source_user_status', sa.String(length=100), nullable=True),
    sa.Column('source_system_status', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'critical', 'unclassified')", name=op.f('ck_work_orders_priority')),
    sa.CheckConstraint("status IN ('created', 'approved', 'in_progress', 'completed', 'cancelled')", name=op.f('ck_work_orders_status')),
    sa.CheckConstraint("work_order_type IN ('corrective', 'preventive', 'inspection', 'unclassified')", name=op.f('ck_work_orders_type')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_work_orders_equipment_id_equipment'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_work_orders_canonical_id')),
    sa.UniqueConstraint('work_order_number', name=op.f('uq_work_orders_work_order_number'))
    )
    op.create_index('ix_work_orders_equipment_id', 'work_orders', ['equipment_id'], unique=False)
    op.create_index('ix_work_orders_opened_at', 'work_orders', ['opened_at'], unique=False)
    op.create_index('ix_work_orders_status', 'work_orders', ['status'], unique=False)
    op.create_table('asset_identifiers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('identifier_type', sa.String(length=100), nullable=False),
    sa.Column('identifier_value', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('((equipment_id IS NOT NULL)::integer + (component_id IS NOT NULL)::integer) = 1', name=op.f('ck_asset_identifiers_exactly_one_asset')),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_asset_identifiers_component_id_components'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_asset_identifiers_equipment_id_equipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_identifiers')),
    sa.UniqueConstraint('source_system', 'identifier_type', 'identifier_value', name='uq_asset_identifiers_source_type_value')
    )
    op.create_index('ix_asset_identifiers_component_id', 'asset_identifiers', ['component_id'], unique=False)
    op.create_index('ix_asset_identifiers_equipment_id', 'asset_identifiers', ['equipment_id'], unique=False)
    op.create_index('ix_asset_identifiers_value', 'asset_identifiers', ['identifier_value'], unique=False)
    op.create_table('failure_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('event_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downtime_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'under_investigation', 'resolved', 'closed')", name=op.f('ck_failure_events_status')),
    sa.CheckConstraint('downtime_minutes IS NULL OR downtime_minutes >= 0', name=op.f('ck_failure_events_nonnegative_downtime')),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_failure_events_valid_time_range')),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_failure_events_component_id_components'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_failure_events_equipment_id_equipment'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failure_events')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_failure_events_canonical_id')),
    sa.UniqueConstraint('event_number', name=op.f('uq_failure_events_event_number'))
    )
    op.create_index('ix_failure_events_component_id', 'failure_events', ['component_id'], unique=False)
    op.create_index('ix_failure_events_equipment_id', 'failure_events', ['equipment_id'], unique=False)
    op.create_index('ix_failure_events_started_at', 'failure_events', ['started_at'], unique=False)
    op.create_index('ix_failure_events_status', 'failure_events', ['status'], unique=False)
    op.create_table('maintenance_activities',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('activity_code', sa.String(length=100), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'in_progress', 'completed', 'cancelled')", name=op.f('ck_maintenance_activities_status')),
    sa.CheckConstraint('sequence_number > 0', name=op.f('ck_maintenance_activities_positive_sequence')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_maintenance_activities_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_activities')),
    sa.UniqueConstraint('work_order_id', 'sequence_number', name='uq_maintenance_activities_work_order_sequence')
    )
    op.create_index('ix_maintenance_activities_activity_type', 'maintenance_activities', ['activity_type'], unique=False)
    op.create_index('ix_maintenance_activities_work_order_id', 'maintenance_activities', ['work_order_id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sensor_type', sa.String(length=100), nullable=False),
    sa.Column('engineering_unit', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'maintenance', 'retired')", name=op.f('ck_sensors_status')),
    sa.CheckConstraint('((equipment_id IS NOT NULL)::integer + (component_id IS NOT NULL)::integer) = 1', name=op.f('ck_sensors_exactly_one_asset')),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_sensors_component_id_components'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_sensors_equipment_id_equipment'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensors')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_sensors_canonical_id')),
    sa.UniqueConstraint('tag_name', name=op.f('uq_sensors_tag_name'))
    )
    op.create_index('ix_sensors_component_id', 'sensors', ['component_id'], unique=False)
    op.create_index('ix_sensors_equipment_id', 'sensors', ['equipment_id'], unique=False)
    op.create_index('ix_sensors_sensor_type', 'sensors', ['sensor_type'], unique=False)
    op.create_table('work_order_notifications',
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['maintenance_notifications.id'], name=op.f('fk_work_order_notifications_notification_id_maintenance_notifications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_notifications_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_order_id', 'notification_id', name=op.f('pk_work_order_notifications'))
    )
    op.create_index('ix_work_order_notifications_notification_id', 'work_order_notifications', ['notification_id'], unique=False)
    op.create_table('activity_spare_parts',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('spare_part_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_activity_spare_parts_positive_quantity')),
    sa.ForeignKeyConstraint(['activity_id'], ['maintenance_activities.id'], name=op.f('fk_activity_spare_parts_activity_id_maintenance_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], name=op.f('fk_activity_spare_parts_spare_part_id_spare_parts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('activity_id', 'spare_part_id', name=op.f('pk_activity_spare_parts'))
    )
    op.create_table('activity_targets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('((equipment_id IS NOT NULL)::integer + (component_id IS NOT NULL)::integer) = 1', name=op.f('ck_activity_targets_exactly_one_asset')),
    sa.ForeignKeyConstraint(['activity_id'], ['maintenance_activities.id'], name=op.f('fk_activity_targets_activity_id_maintenance_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_activity_targets_component_id_components'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_activity_targets_equipment_id_equipment'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_targets')),
    sa.UniqueConstraint('activity_id', 'component_id', name='uq_activity_targets_activity_component'),
    sa.UniqueConstraint('activity_id', 'equipment_id', name='uq_activity_targets_activity_equipment')
    )
    op.create_index('ix_activity_targets_component_id', 'activity_targets', ['component_id'], unique=False)
    op.create_index('ix_activity_targets_equipment_id', 'activity_targets', ['equipment_id'], unique=False)
    op.create_table('activity_technicians',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['maintenance_activities.id'], name=op.f('fk_activity_technicians_activity_id_maintenance_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], name=op.f('fk_activity_technicians_technician_id_technicians'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('activity_id', 'technician_id', name=op.f('pk_activity_technicians'))
    )
    op.create_table('alarms',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('alarm_code', sa.String(length=100), nullable=False),
    sa.Column('alarm_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_alarms_severity')),
    sa.CheckConstraint("status IN ('active', 'acknowledged', 'cleared')", name=op.f('ck_alarms_status')),
    sa.CheckConstraint('cleared_at IS NULL OR cleared_at >= triggered_at', name=op.f('ck_alarms_valid_time_range')),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_alarms_sensor_id_sensors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alarms')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_alarms_canonical_id'))
    )
    op.create_index('ix_alarms_sensor_id', 'alarms', ['sensor_id'], unique=False)
    op.create_index('ix_alarms_status', 'alarms', ['status'], unique=False)
    op.create_index('ix_alarms_triggered_at', 'alarms', ['triggered_at'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('failure_event_id', sa.Uuid(), nullable=True),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('proposed_cause_id', sa.Uuid(), nullable=True),
    sa.Column('source_key', sa.String(length=128), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('assertion_status', sa.String(length=30), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('subject_text', sa.String(length=500), nullable=True),
    sa.Column('predicate', sa.String(length=100), nullable=True),
    sa.Column('object_text', sa.Text(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('engineering_unit', sa.String(length=50), nullable=True),
    sa.Column('source_section', sa.String(length=100), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('review_status', sa.String(length=30), server_default=sa.text("'unreviewed'"), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('extractor_version', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assertion_status IN ('observed', 'suspected', 'confirmed', 'negated', 'recommended', 'executed')", name=op.f('ck_claims_assertion_status')),
    sa.CheckConstraint("claim_type IN ('observation', 'measurement', 'negative_finding', 'symptom', 'failure_mode', 'damage', 'probable_cause', 'risk', 'diagnostic_result', 'recommended_activity', 'executed_activity', 'operational_constraint')", name=op.f('ck_claims_type')),
    sa.CheckConstraint("review_status IN ('unreviewed', 'accepted', 'rejected')", name=op.f('ck_claims_review_status')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_claims_confidence_range')),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_claims_component_id_components'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_claims_equipment_id_equipment'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], name=op.f('fk_claims_failure_event_id_failure_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_cause_id'], ['causes.id'], name=op.f('fk_claims_proposed_cause_id_causes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('source_key', name=op.f('uq_claims_source_key'))
    )
    op.create_index('ix_claims_component_id', 'claims', ['component_id'], unique=False)
    op.create_index('ix_claims_equipment_id', 'claims', ['equipment_id'], unique=False)
    op.create_index('ix_claims_failure_event_id', 'claims', ['failure_event_id'], unique=False)
    op.create_index('ix_claims_proposed_cause_id', 'claims', ['proposed_cause_id'], unique=False)
    op.create_index('ix_claims_review_status', 'claims', ['review_status'], unique=False)
    op.create_table('damages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('failure_event_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('damage_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_damages_severity')),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_damages_component_id_components'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], name=op.f('fk_damages_failure_event_id_failure_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_damages'))
    )
    op.create_index('ix_damages_component_id', 'damages', ['component_id'], unique=False)
    op.create_index('ix_damages_failure_event_id', 'damages', ['failure_event_id'], unique=False)
    op.create_table('failure_event_causes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('failure_event_id', sa.Uuid(), nullable=False),
    sa.Column('cause_id', sa.Uuid(), nullable=False),
    sa.Column('verification_method', sa.String(length=100), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['cause_id'], ['causes.id'], name=op.f('fk_failure_event_causes_cause_id_causes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], name=op.f('fk_failure_event_causes_failure_event_id_failure_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failure_event_causes')),
    sa.UniqueConstraint('failure_event_id', 'cause_id', name='uq_failure_event_causes_event_cause')
    )
    op.create_table('failure_event_failure_modes',
    sa.Column('failure_event_id', sa.Uuid(), nullable=False),
    sa.Column('failure_mode_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_failure_event_failure_modes_confidence_range')),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], name=op.f('fk_failure_event_failure_modes_failure_event_id_failure_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['failure_modes.id'], name=op.f('fk_failure_event_failure_modes_failure_mode_id_failure_modes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('failure_event_id', 'failure_mode_id', name=op.f('pk_failure_event_failure_modes'))
    )
    op.create_table('failure_event_symptoms',
    sa.Column('failure_event_id', sa.Uuid(), nullable=False),
    sa.Column('symptom_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_failure_event_symptoms_severity')),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], name=op.f('fk_failure_event_symptoms_failure_event_id_failure_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name=op.f('fk_failure_event_symptoms_symptom_id_symptoms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('failure_event_id', 'symptom_id', name=op.f('pk_failure_event_symptoms'))
    )
    op.create_table('observations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('engineering_unit', sa.String(length=50), nullable=False),
    sa.Column('quality', sa.String(length=30), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("quality IN ('good', 'uncertain', 'bad')", name=op.f('ck_observations_quality')),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_observations_sensor_id_sensors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations')),
    sa.UniqueConstraint('sensor_id', 'observed_at', name='uq_observations_sensor_time')
    )
    op.create_index('ix_observations_observed_at', 'observations', ['observed_at'], unique=False)
    op.create_index('ix_observations_sensor_time', 'observations', ['sensor_id', 'observed_at'], unique=False)
    op.create_table('work_order_failure_events',
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('failure_event_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.CheckConstraint("relationship_type IN ('responds_to', 'follow_up')", name=op.f('ck_work_order_failure_events_relationship_type')),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], name=op.f('fk_work_order_failure_events_failure_event_id_failure_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_failure_events_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_order_id', 'failure_event_id', name=op.f('pk_work_order_failure_events'))
    )
    op.create_table('alarm_failure_events',
    sa.Column('alarm_id', sa.Uuid(), nullable=False),
    sa.Column('failure_event_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.CheckConstraint("relationship_type IN ('preceded', 'occurred_during')", name=op.f('ck_alarm_failure_events_relationship_type')),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], name=op.f('fk_alarm_failure_events_alarm_id_alarms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], name=op.f('fk_alarm_failure_events_failure_event_id_failure_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alarm_id', 'failure_event_id', name=op.f('pk_alarm_failure_events'))
    )
    op.create_table('alarm_symptoms',
    sa.Column('alarm_id', sa.Uuid(), nullable=False),
    sa.Column('symptom_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], name=op.f('fk_alarm_symptoms_alarm_id_alarms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name=op.f('fk_alarm_symptoms_symptom_id_symptoms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('alarm_id', 'symptom_id', name=op.f('pk_alarm_symptoms'))
    )
    op.create_table('claim_evidence',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_evidence_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_claim_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'evidence_id', name=op.f('pk_claim_evidence'))
    )
    op.create_table('claim_reviews',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('accepted', 'rejected')", name=op.f('ck_claim_reviews_decision')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_reviews_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_reviews'))
    )
    op.create_index('ix_claim_reviews_claim_id', 'claim_reviews', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_claim_reviews_claim_id', table_name='claim_reviews')
    op.drop_table('claim_reviews')
    op.drop_table('claim_evidence')
    op.drop_table('alarm_symptoms')
    op.drop_table('alarm_failure_events')
    op.drop_table('work_order_failure_events')
    op.drop_index('ix_observations_sensor_time', table_name='observations')
    op.drop_index('ix_observations_observed_at', table_name='observations')
    op.drop_table('observations')
    op.drop_table('failure_event_symptoms')
    op.drop_table('failure_event_failure_modes')
    op.drop_table('failure_event_causes')
    op.drop_index('ix_damages_failure_event_id', table_name='damages')
    op.drop_index('ix_damages_component_id', table_name='damages')
    op.drop_table('damages')
    op.drop_index('ix_claims_review_status', table_name='claims')
    op.drop_index('ix_claims_proposed_cause_id', table_name='claims')
    op.drop_index('ix_claims_failure_event_id', table_name='claims')
    op.drop_index('ix_claims_equipment_id', table_name='claims')
    op.drop_index('ix_claims_component_id', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_alarms_triggered_at', table_name='alarms')
    op.drop_index('ix_alarms_status', table_name='alarms')
    op.drop_index('ix_alarms_sensor_id', table_name='alarms')
    op.drop_table('alarms')
    op.drop_table('activity_technicians')
    op.drop_index('ix_activity_targets_equipment_id', table_name='activity_targets')
    op.drop_index('ix_activity_targets_component_id', table_name='activity_targets')
    op.drop_table('activity_targets')
    op.drop_table('activity_spare_parts')
    op.drop_index('ix_work_order_notifications_notification_id', table_name='work_order_notifications')
    op.drop_table('work_order_notifications')
    op.drop_index('ix_sensors_sensor_type', table_name='sensors')
    op.drop_index('ix_sensors_equipment_id', table_name='sensors')
    op.drop_index('ix_sensors_component_id', table_name='sensors')
    op.drop_table('sensors')
    op.drop_index('ix_maintenance_activities_work_order_id', table_name='maintenance_activities')
    op.drop_index('ix_maintenance_activities_activity_type', table_name='maintenance_activities')
    op.drop_table('maintenance_activities')
    op.drop_index('ix_failure_events_status', table_name='failure_events')
    op.drop_index('ix_failure_events_started_at', table_name='failure_events')
    op.drop_index('ix_failure_events_equipment_id', table_name='failure_events')
    op.drop_index('ix_failure_events_component_id', table_name='failure_events')
    op.drop_table('failure_events')
    op.drop_index('ix_asset_identifiers_value', table_name='asset_identifiers')
    op.drop_index('ix_asset_identifiers_equipment_id', table_name='asset_identifiers')
    op.drop_index('ix_asset_identifiers_component_id', table_name='asset_identifiers')
    op.drop_table('asset_identifiers')
    op.drop_index('ix_work_orders_status', table_name='work_orders')
    op.drop_index('ix_work_orders_opened_at', table_name='work_orders')
    op.drop_index('ix_work_orders_equipment_id', table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index('ix_evidence_document_chunk_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_equipment_operating_states_equipment_time', table_name='equipment_operating_states')
    op.drop_table('equipment_operating_states')
    op.drop_index('ix_components_equipment_id', table_name='components')
    op.drop_index('ix_components_component_type', table_name='components')
    op.drop_table('components')
    op.drop_index('ix_equipment_production_line_id', table_name='equipment')
    op.drop_index('ix_equipment_equipment_type', table_name='equipment')
    op.drop_table('equipment')
    op.drop_index('ix_document_chunks_document_version_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_production_lines_plant_id', table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_table('notification_concept_links')
    op.drop_index('ix_document_versions_document_id', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('technicians')
    op.drop_table('symptoms')
    op.drop_table('spare_parts')
    op.drop_table('semantic_concepts')
    op.drop_table('plants')
    op.drop_table('operating_states')
    op.drop_table('maintenance_notifications')
    op.drop_table('failure_modes')
    op.drop_index('ix_documents_document_type', table_name='documents')
    op.drop_table('documents')
    op.drop_table('causes')
    # ### end Alembic commands ###
